name: Theme deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          shopify theme push \
            --json \
            --ignore "config/settings_data.json" "templates/*.json" "sections/*.json" \
            --theme 182280847744 \
            --store ${{ secrets.SHOPIFY_STORE }} \
            --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }} \
            --allow-live
